### ISSUE TITLE
Error logs: Publishing changes from background threads is not allowed

### ISSUE THREAD

**Issue by Wallman** [marwaniaaj/AuthLoginSwiftUI#1]
This project is receiving error logs: `Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.`

How could that best be solved?

**Comment by Wallman** [comment]
Could `@MainActor` on AuthManager maybe solve the issue?

**Comment by marwaniaaj** [comment]
Yes, `@MainActor` on `AuthManager` class will solve the issue.
I will update the code.
@Wallman thank you for the feedback.
